### ISSUE TITLE
Error after upgrade to 1.4.0

### ISSUE THREAD

**Issue by kacperpaluch** [piazzatron/anki-smart-notes#17]
Error after upgrade to 1.4.0:

```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-14.5-arm64-arm-64bit

When loading Smart Notes - AI Generated Fields with ChatGPT-4o 35 etc:
Traceback (most recent call last):
  File "urllib3.connection", line 196, in _new_conn
  File "urllib3.util.connection", line 60, in create_connection
  File "socket", line 954, in getaddrinfo
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3.connectionpool", line 789, in urlopen
  File "urllib3.connectionpool", line 490, in _make_request
  File "urllib3.connectionpool", line 466, in _make_request
  File "urllib3.connectionpool", line 1095, in _validate_conn
  File "urllib3.connection", line 615, in connect
  File "urllib3.connection", line 203, in _new_conn
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x135065850>: Failed to resolve 'api2.amplitude.com' ([Errno 8] nodename nor servname provided, or not known)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "requests.adapters", line 589, in send
  File "urllib3.connectionpool", line 843, in urlopen
  File "urllib3.util.retry", line 519, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api2.amplitude.com', port=443): Max retries exceeded with url: /2/httpapi (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x135065850>: Failed to resolve 'api2.amplitude.com' ([Errno 8] nodename nor servname provided, or not known)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/MyUserName/Library/Application Support/Anki2/addons21/1531888719/__init__.py", line 65, in <module>
    from .src.main import main
  File "/Users/MyUserName/Library/Application Support/Anki2/addons21/1531888719/src/main.py", line 21, in <module>
    from .hooks import setup_hooks
  File "/Users/MyUserName/Library/Application Support/Anki2/addons21/1531888719/src/hooks.py", line 36, in <module>
    from .processor import Processor
  File "/Users/MyUserName/Library/Application Support/Anki2/addons21/1531888719/src/processor.py", line 33, in <module>
    from .sentry import sentry
  File "/Users/MyUserName/Library/Application Support/Anki2/addons21/1531888719/src/sentry.py", line 194, in <module>
    sentry = init_sentry()
  File "/Users/MyUserName/Library/Application Support/Anki2/addons21/1531888719/src/sentry.py", line 165, in init_sentry
    requests.post(
  File "requests.api", line 115, in post
  File "requests.api", line 59, in request
  File "requests.sessions", line 589, in request
  File "requests.sessions", line 703, in send
  File "requests.adapters", line 622, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api2.amplitude.com', port=443): Max retries exceeded with url: /2/httpapi (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x135065850>: Failed to resolve 'api2.amplitude.com' ([Errno 8] nodename nor servname provided, or not known)"))

```

**Comment by piazzatron** [comment]
Fixed in v1.4.2
