### ISSUE TITLE
Error after latest upgrade

### ISSUE THREAD

**Issue by Positron010** [piazzatron/anki-smart-notes#32]
The addon fails to load after the latest upgrade, with the following debug log (name of home folder removed):

```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

When loading Smart Notes - AI Notes  TTS with with ChatGPT-4o Claude ElevenLabs etc:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1531888719\__init__.py", line 72, in <module>
    from .src.main import main
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1531888719\src\main.py", line 22, in <module>
    from .field_resolver import FieldResolver
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1531888719\src\field_resolver.py", line 25, in <module>
    from .app_state import (
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1531888719\src\app_state.py", line 39, in <module>
    from .sentry import run_async_in_background_with_sentry
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1531888719\src\sentry.py", line 31, in <module>
    from sentry_sdk.types import Event
ModuleNotFoundError: No module named 'sentry_sdk.types'
```

Thanks

**Comment by piazzatron** [comment]
Hey @Positron010 sorry you faced this, I just released a 2.1.7 which should fix it. Let me know.

(Weird issue, must be platform specific)

**Comment by Positron010** [comment]
Hey,
Thanks, the new release fixed the issue, and the plugin loads successfully now.

**Comment by piazzatron** [comment]
Sweet! Thanks for flagging this one
